FROM node:14-alpine as build

WORKDIR /react/blogapi
COPY ./react/blogapi/package.json .
RUN npm install
COPY ./react/blogapi .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /react/blogapi/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
