version: '3'

services:
  backend:
    build:
      context: ./django
    container_name: django-react_backend
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./react/blogapi
    container_name: django-react_frontend
    ports:
      - 80:8080
    depends_on:
      - backend
