version: '3'

services:
  backend:
    build:
      context: ./django
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./react/blogapi
#     command: ['nginx', '-g', 'daemon off;']
    ports:
      - 80:8080
